# Generated by Django 4.2.5 on 2023-09-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AquaAccount',
            fields=[
                ('id_aqua_account', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_mail', models.CharField(max_length=60)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aqua_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AquaDecorator',
            fields=[
                ('id_aqua_decorator', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aqua_decorator',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AquaMaker',
            fields=[
                ('id_aqua_maker', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aqua_maker',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AquariumTank',
            fields=[
                ('id_aquarium_tank', models.BigAutoField(primary_key=True, serialize=False)),
                ('size_width', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('size_height', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('size_length', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'aquarium_tank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id_asset', models.BigAutoField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(blank=True, max_length=45, null=True)),
                ('asset_size_flag', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id_fish', models.BigAutoField(primary_key=True, serialize=False)),
                ('fish_name', models.CharField(blank=True, max_length=45, null=True)),
                ('fish_size', models.IntegerField(blank=True, null=True)),
                ('min_ph', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('max_ph', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('min_degree', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('max_degree', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('fish_character', models.CharField(blank=True, max_length=45, null=True)),
                ('info', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'fish',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id_ground', models.BigAutoField(primary_key=True, serialize=False)),
                ('ground_name', models.CharField(blank=True, max_length=45, null=True)),
                ('ground_size', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'ground',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Heater',
            fields=[
                ('id_heater', models.BigAutoField(primary_key=True, serialize=False)),
                ('heater_name', models.CharField(blank=True, max_length=45, null=True)),
                ('heater_min_power', models.IntegerField(blank=True, null=True)),
                ('heater_max_power', models.IntegerField(blank=True, null=True)),
                ('min_capacity', models.IntegerField(blank=True, null=True)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'heater',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id_lamp', models.BigAutoField(primary_key=True, serialize=False)),
                ('lamp_name', models.CharField(blank=True, max_length=60, null=True)),
                ('power', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'lamp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id_plant', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'plant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id_pump', models.BigAutoField(primary_key=True, serialize=False)),
                ('pump_name', models.CharField(blank=True, max_length=60, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('pump_capacity', models.IntegerField(blank=True, null=True)),
                ('water_gauge', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'pump',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TankObject',
            fields=[
                ('id_tank_object', models.BigAutoField(primary_key=True, serialize=False)),
                ('tank_name', models.CharField(blank=True, max_length=80, null=True)),
                ('id_tank_picture', models.IntegerField(blank=True, null=True)),
                ('is_favourite_tank', models.IntegerField(blank=True, null=True)),
                ('id_aqua_account', models.ForeignKey(db_column='id_aqua_account', on_delete=django.db.models.deletion.CASCADE, to='aqua.aquaaccount')),
                ('id_aqua_decorator', models.ForeignKey(db_column='id_aqua_decorator', on_delete=django.db.models.deletion.PROTECT, to='aqua.aquadecorator')),
                ('id_aqua_maker', models.ForeignKey(db_column='id_aqua_maker', on_delete=django.db.models.deletion.PROTECT, to='aqua.aquamaker')),
            ],
            options={
                'db_table': 'tank_object',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FishConflict',
            fields=[
                ('id_fish_conflict', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_second_fish', models.IntegerField(blank=True, null=True)),
                ('id_first_fish', models.ForeignKey(blank=True, db_column='id_first_fish', null=True, on_delete=django.db.models.deletion.PROTECT, to='aqua.fish')),
            ],
            options={
                'db_table': 'fish_conflict',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='aquamaker',
            name='id_aquarium_tank',
            field=models.ForeignKey(db_column='id_aquarium_tank', on_delete=django.db.models.deletion.CASCADE, to='aqua.aquariumtank'),
        ),
        migrations.AddField(
            model_name='aquamaker',
            name='id_heater',
            field=models.ForeignKey(db_column='id_heater', on_delete=django.db.models.deletion.PROTECT, to='aqua.heater'),
        ),
        migrations.AddField(
            model_name='aquamaker',
            name='id_lamp',
            field=models.ForeignKey(db_column='id_lamp', on_delete=django.db.models.deletion.PROTECT, to='aqua.lamp'),
        ),
        migrations.AddField(
            model_name='aquamaker',
            name='id_pump',
            field=models.ForeignKey(db_column='id_pump', on_delete=django.db.models.deletion.PROTECT, to='aqua.pump'),
        ),
        migrations.CreateModel(
            name='AquaLife',
            fields=[
                ('id_aqua_life_fish', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_fish_life_time', models.DateField(blank=True, null=True)),
                ('fish_life_status', models.BooleanField(blank=True, null=True)),
                ('fish_nickname', models.CharField(blank=True, max_length=259, null=True)),
                ('id_fish', models.ForeignKey(db_column='id_fish', on_delete=django.db.models.deletion.PROTECT, to='aqua.fish')),
                ('id_tank_object', models.ForeignKey(blank=True, db_column='id_tank_object', null=True, on_delete=django.db.models.deletion.CASCADE, to='aqua.tankobject')),
            ],
            options={
                'db_table': 'aqua_life',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AquaHistory',
            fields=[
                ('id_aqua_history', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_info', models.CharField(blank=True, max_length=500, null=True)),
                ('id_aqua_account', models.ForeignKey(blank=True, db_column='id_aqua_account', null=True, on_delete=django.db.models.deletion.CASCADE, to='aqua.aquaaccount')),
            ],
            options={
                'db_table': 'aqua_history',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='aquadecorator',
            name='id_asset',
            field=models.ForeignKey(db_column='id_asset', on_delete=django.db.models.deletion.PROTECT, to='aqua.asset'),
        ),
        migrations.AddField(
            model_name='aquadecorator',
            name='id_ground',
            field=models.ForeignKey(db_column='id_ground', on_delete=django.db.models.deletion.PROTECT, to='aqua.ground'),
        ),
        migrations.AddField(
            model_name='aquadecorator',
            name='id_plant',
            field=models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.PROTECT, to='aqua.plant'),
        ),
    ]
