# Generated by Django 4.2.5 on 2023-09-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='max_degree',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='max_ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='min_degree',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='min_ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fishconflict',
            name='id_first_fish',
            field=models.ForeignKey(blank=True, db_column='id_first_fish', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fish_conflict_first_fish', to='aqua.fish'),
        ),
        migrations.AlterField(
            model_name='fishconflict',
            name='id_second_fish',
            field=models.ForeignKey(blank=True, db_column='id_second_fish', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fish_conflict_second_fish', to='aqua.fish'),
        ),
    ]
