# Generated by Django 4.2.5 on 2023-09-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0002_alter_fish_max_degree_alter_fish_max_ph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishconflict',
            name='id_first_fish',
            field=models.ForeignKey(blank=True, db_column='id_first_fish', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fish_conflict_first_fish', to='aqua.fish'),
        ),
        migrations.AlterField(
            model_name='fishconflict',
            name='id_second_fish',
            field=models.ForeignKey(blank=True, db_column='id_second_fish', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fish_conflict_second_fish', to='aqua.fish'),
        ),
    ]
