# Generated by Django 4.2.5 on 2023-09-11 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0003_alter_fishconflict_id_first_fish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquamaker',
            name='id_heater',
            field=models.ForeignKey(db_column='id_heater', on_delete=django.db.models.deletion.CASCADE, to='aqua.heater'),
        ),
    ]
