# Generated by Django 4.2.5 on 2023-09-11 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0004_alter_aquamaker_id_heater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankobject',
            name='id_aqua_maker',
            field=models.ForeignKey(db_column='id_aqua_maker', on_delete=django.db.models.deletion.CASCADE, to='aqua.aquamaker'),
        ),
    ]
