# Generated by Django 4.2.5 on 2023-09-11 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0005_alter_tankobject_id_aqua_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquadecorator',
            name='id_asset',
            field=models.ForeignKey(db_column='id_asset', on_delete=django.db.models.deletion.CASCADE, to='aqua.asset'),
        ),
        migrations.AlterField(
            model_name='aquadecorator',
            name='id_ground',
            field=models.ForeignKey(db_column='id_ground', on_delete=django.db.models.deletion.CASCADE, to='aqua.ground'),
        ),
        migrations.AlterField(
            model_name='aquadecorator',
            name='id_plant',
            field=models.ForeignKey(db_column='id_plant', on_delete=django.db.models.deletion.CASCADE, to='aqua.plant'),
        ),
    ]
