# Generated by Django 4.2.5 on 2023-09-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0006_alter_aquadecorator_id_asset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pump',
            old_name='pump_capacity',
            new_name='max_capacity',
        ),
    ]
